---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fsp

<!-- badges: start -->
<!-- badges: end -->

Experimental functions to assist with producing the Food Statistics Pocketbook

## Installation

You can install the development version of fsp from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("FoodchainStats/fsp")
```


## JOBS03 workflow


```{r jobs03, message=FALSE, warning=FALSE}
library(fsp)

j <- acquire_jobs03()

jobs03 <- get_jobs03_data(j)

knitr::kable(head(jobs03))

```

## Agricultural workforce

```{r, message=FALSE, warning=FALSE}
library(fsp)
w <- acquire_ag_workforce()

ag_workforce <- fsp::get_ag_workforce(w)

knitr::kable(head(ag_workforce))


```

## Process

```{r process, message=FALSE, warning=FALSE}

lvls <- c("Agriculture",
          "Fishing",
          "Manufacturing",
          "Wholesale",
          "Retail",
          "Catering")

ag_gb <- fsp::compile_ag()

food <- fsp::jobs03_sectors() |> 
  dplyr::left_join(fsp::get_jobs03_data()) |> 
  dplyr::group_by(sector, date) |> 
  dplyr::summarise(value = sum(value)) |> 
  dplyr::bind_rows(ag_gb) |> 
  dplyr::mutate(sector = forcats::fct(sector, levels = lvls))



food |> 
  dplyr::filter(date >= "2020-01-01") |> 
  ggplot2::ggplot() +
  ggplot2::geom_point(ggplot2::aes(x = date, y = value, colour = sector)) +
  ggplot2::geom_line(ggplot2::aes(x = date, y = value, colour = sector))


food |>
  dplyr::group_by(sector) |>
  dplyr::slice_max(date) |> 
  knitr::kable()
  

```

