---
title: "Getting started with fsp"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## What this package is supposed to be

The idea is to collate a set of functions to assist with updating sections of
the pocketbook, together with examples of using them in the articles on this
site to make guidance for producing items in the publication.

## Installation

You can install the development version of fsp from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("FoodchainStats/fsp")
```

## Usage

There are several broad categories of functions, generally aimed at helping to
access datasets that underlie pocketbook content, and wrangle it into useful
shape.

`url_*` functions simply store the address of where the datasets are. They are
used by other fsp functions to download data. If things arent working the first
thing you can do is manually check these url to see that they are pointing to
the right data.

`acquire_*` functions actually download data. By default they download into a
temporary file, but you can specify a folder to download to. These functions
return the path to the downloaded file. You can use the output of `acquire_*`
functions with, eg `read.csv()` or other similar functions. Alternatively...

`get_*` functions wrap around `url` and `acquire`, reading in data and returning
a tibble. In most cases they also do a bit of light processing, eg cleaning up
variable names. For some source datasets they may return an element of the
underlying data, such as only the monthly or yearly data, or metadata about the
dataset contents.

