---
title: "Agri-food chain employment"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

```

## Workflow

The first step is to acquire the raw data.

```{r raw-data, warning=FALSE}

library(fsp)

lvls <- c("Agriculture",
          "Fishing",
          "Manufacturing",
          "Wholesale",
          "Retail",
          "Catering")

ag_gb <- fsp::compile_ag_workforce()
jobs03 <- fsp::get_jobs03_data()

food <- fsp::jobs03_sectors() |> 
  dplyr::left_join(jobs03, by = dplyr::join_by(sic_division)) |> 
  dplyr::group_by(sector, date) |> 
  dplyr::summarise(value = sum(value)) |> 
  dplyr::bind_rows(ag_gb) |> 
  dplyr::mutate(sector = forcats::fct(sector, levels = lvls))

food |> 
  dplyr::arrange(desc(date)) |> 
  head() |> 
  knitr::kable()

```

Since the agricultural workforce data is annual, and the JOBS03 data is
quarterly, the latest year may not include figures for agriculture. Lets get
some yearly averages, and we will calculate some percentage changes in case they
come in useful.


```{r}

fsp_food <- food |> 
  dplyr::mutate(year = lubridate::year(date)) |> 
  dplyr::group_by(sector, year) |> 
  dplyr::summarise(value = mean(value)) |> 
  dplyr::group_by(sector) |> 
  dplyr::mutate(yoy_pct_change = round((value/dplyr::lag(value) - 1)*100, 2)) |> 
  dplyr::group_by(year) |> 
  dplyr::mutate(pct_of_tot = round(value/sum(value) * 100, 2)) 

fsp_food |> 
  dplyr::filter(year == 2022) |>
  knitr::kable()


```

```{r}

x <- fsp_food |> 
dplyr::mutate(total = "Total Agri-Food",
              food_chain = dplyr::case_when(sector != "Agriculture" ~ "Total Food"),
              ag_fish = dplyr::case_when(sector %in% c("Agriculture", "Fishing") ~ "Agriculture (including fishing)")) 


x |> 
  dplyr::filter(year == 2022) |> 
  dplyr::group_by(ag_fish) |> 
  # dplyr::select(sector, value) |> 
  dplyr::summarise(tot = sum(value))



```

